---
name: Link Checker
on: [push, workflow_dispatch]

jobs:
  check_links:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: internal
            options: --exclude-external
          - label: external
            options: --exclude-internal
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install broken-link-checker -g
    - name: Check ${{ matrix.label }} links
      run: blc https://badssl.com ${{ matrix.options }} --recursive --ordered | tee ${{ matrix.label }}_data.txt
    - name: Upload ${{ matrix.label }} data
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.label }}_data
        path: ${{ matrix.label }}_data.txt
  generate_report:
    needs: check_links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: internal
          - label: external
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
          name: ${{ matrix.label }}_data
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Generate a report for ${{ matrix.label }} links
      run: python ./link_checker/generate_report.py ${{ matrix.label }}_data.txt | tee ${{ matrix.label }}_report.md
    - name: Clean up the report if its empty
      run: find . -name ${{ matrix.label }}_report.md -size 0 -exec rm -v {} \; -print
    - name: Upload ${{ matrix.label }} report
      uses: actions/upload-artifact@v2
      id: report
      with:
        name: ${{ matrix.label }}_report
        path: ${{ matrix.label }}_report.md
    - name: Create an issue for ${{ matrix.label }} links
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: Latest report for broken ${{ matrix.label }} links
        content-filepath: ${{ matrix.label }}_report.md
        labels: report, automated issue
