---
name: Link Checker
on:
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        switches: [-ero, -iro]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install broken-link-checker -g
    - run: blc https://ebwiki.org ${{ matrix.switches }}
