---
name: Link Check
on:
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    name: Link Check
    steps:
      - uses: filiph/linkcheck-action@e79e9bd8623a07610ab1e3200b01cc69bb34846d
        with:
          arguments: https://ebwiki.org
