---
name: Link Checker
on:
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: internal
            options: --exclude-external
          - label: external
            options: --exclude-internal
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm install broken-link-checker -g
    - name: Check ${{ matrix.label }} links
      run: blc https://example.com ${{ matrix.options }} --recursive --ordered | tee ${{ matrix.label }}_link_report.txt
    - name: Upload ${{ matrix.label }} report
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.label }}_link_report.txt
        path: ${{ matrix.label }}_link_report.txt
