---
name: Link Checker
on:
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - label: internal
            options: --exclude-external
          - label: external
            options: --exclude-internal
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install broken-link-checker -g
    - name: Check ${{ matrix.label }} links
      run: blc https://ebwiki.org ${{ matrix.options }} --recursive --ordered
