---
name: Link Check
on:
  workflow_dispatch:

jobs:
  link_check:
    runs-on: ubuntu-latest
    name: Link Check
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install broken-link-checker -g
    - run: blc https://ebwiki.org -ero
